import Head from 'next/head'
import Image from 'next/image'
import MainPage from '../components/MainPage'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <MainPage />
     
    </div>
  )
}
